config setup
    uniqueids=no

conn nss-tunnel
    auto=start
    type=tunnel
    authby=rsasig
    keyexchange=ikev2
    ike=aes256-sha2;modp2048
    phase2alg=aes256-sha2
    left=20.0.0.3
    leftid=@vm3.nss.local
    leftsubnet=30.0.0.0/24
    leftcert=vm3.crt
    right=20.0.0.2
    rightid=@vm2.nss.local
    rightsubnet=10.0.0.0/24
    narrowing=yes

conn nss-web-selector
    also=nss-tunnel
    leftprotoport=tcp/80
    auto=add

conn nss-transport
    auto=add
    type=transport
    authby=rsasig
    keyexchange=ikev2
    ike=aes256-sha2;modp2048
    phase2alg=aes256-sha2
    left=20.0.0.3
    leftid=@vm3.nss.local
    leftcert=vm3.crt
    right=20.0.0.2
    rightid=@vm2.nss.local
